import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Power Balloon",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="pt-br">
      <body className="bg-dark text-white flex flex-col min-h-screen">
        <Cabecalho/>
        <main className="flex-grow bg-transparent">
          {children}
        </main>
        <Rodape/>
      </body>
    </html>
  );
}
